"""empty message

Revision ID: be7ae095facb
Revises:
Create Date: 2026-05-01 01:58:17.573080

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be7ae095facb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "divisions",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_divisions")),
    )
    op.create_index(op.f("ix_divisions_code"), "divisions", ["code"], unique=True)
    op.create_table(
        "referees",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_referees")),
        sa.UniqueConstraint("name", name=op.f("uq_referees_name")),
    )
    op.create_table(
        "seasons",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_seasons")),
        sa.UniqueConstraint("name", name=op.f("uq_seasons_name")),
    )
    op.create_table(
        "teams",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_teams")),
        sa.UniqueConstraint("name", name=op.f("uq_teams_name")),
    )
    op.create_table(
        "matches",
        sa.Column("season", sa.String(length=512), nullable=False),
        sa.Column("home_team", sa.String(length=512), nullable=False),
        sa.Column("away_team", sa.String(length=512), nullable=False),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("referee", sa.String(length=512), nullable=False),
        sa.Column("division", sa.String(length=10), nullable=False),
        sa.Column("full_time_home_goals", sa.Integer(), nullable=False),
        sa.Column("full_time_away_goals", sa.Integer(), nullable=False),
        sa.Column("full_time_result", sa.String(length=10), nullable=False),
        sa.Column("half_time_home_goals", sa.Integer(), nullable=True),
        sa.Column("half_time_away_goals", sa.Integer(), nullable=True),
        sa.Column("half_time_result", sa.String(length=10), nullable=True),
        sa.Column("home_shots", sa.Integer(), server_default="0", nullable=False),
        sa.Column("away_shots", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "home_shots_on_target", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "away_shots_on_target", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("home_fouls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("away_fouls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("home_corners", sa.Integer(), server_default="0", nullable=False),
        sa.Column("away_corners", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "home_yellow_cards", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "away_yellow_cards", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("home_red_cards", sa.Integer(), server_default="0", nullable=False),
        sa.Column("away_red_cards", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team"], ["teams.name"], name=op.f("fk_matches_away_team_teams")
        ),
        sa.ForeignKeyConstraint(
            ["division"], ["divisions.code"], name=op.f("fk_matches_division_divisions")
        ),
        sa.ForeignKeyConstraint(
            ["home_team"], ["teams.name"], name=op.f("fk_matches_home_team_teams")
        ),
        sa.ForeignKeyConstraint(
            ["referee"], ["referees.name"], name=op.f("fk_matches_referee_referees")
        ),
        sa.ForeignKeyConstraint(
            ["season"], ["seasons.name"], name=op.f("fk_matches_season_seasons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint(
            "season",
            "home_team",
            "away_team",
            "match_date",
            name=op.f("uq_matches_season_home_team_away_team_match_date"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    op.drop_table("teams")
    op.drop_table("seasons")
    op.drop_table("referees")
    op.drop_index(op.f("ix_divisions_code"), table_name="divisions")
    op.drop_table("divisions")
    # ### end Alembic commands ###
